name = "StandardCurves"
uuid = "afce657e-2d8e-41fb-8ae7-e8fa2da28d11"
authors = ["Nicholas Stone <nicholasestone@proton.me>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[compat]
LinearAlgebra = "1.11.0"
RecipesBase = "1.3.4"
